### ISSUE TITLE
Custom Height issue

### ISSUE THREAD

**Issue by bennettl** [booncon/slippry#85]
I need a custom height for my slideshow, the natural images are too large. When setting the height via css, the images are distorted, and the slippry box itself fills the natural height of the images.
![screen shot 2015-08-03 at 2 37 05 pm](https://cloud.githubusercontent.com/assets/1672224/9048340/52576c7c-39ed-11e5-8007-8d6b9cd552a7.png)

**Comment by sftsk** [comment]
In this case you will have to change the original css of slippry to suit your use-case. You will have to set a (fixed) height on the slide-elements and make sure the images within are positioned correctly.
You might want to centre them and have them crop off left and right to fill up the whole space.
Right now your problem is probably that the width gets set to `100%` but it should be `auto` otherwise it stretches them weirdly.

I hope this gets you to the right direction!
